# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Chris Flemming
tagline:             'Software Engineer'
url:                 http://cpf.id.au
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist

# About/contact
author:
  name:              Chris Flemming
  url:               http://cpf.id.au

# For use with jekyll SEO plugin
twitter:
  username: chris_flemming

# For use with jekyll SEO plugin
social:
  name: Chris Flemming
  links: ["https://github.com/chrisflemming", "https://au.linkedin.com/pub/chris-flemming/a/58a/653", "https://twitter.com/chris_flemming"]

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/chrisflemming/chrisflemming.github.io

# Pages to show in header
pages_list:       
  About: '/about'
  Archive: '/archive'
